name: Code analysis

on:
  push:
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    name: Validate composer.json and run Psalm

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions:5.7.7
        with:
          composer_ignore_platform_reqs: true
